### ISSUE TITLE
Error when running any command

### ISSUE THREAD

**Issue by exitface** [djui/alias-tips#26]
On master any command I run gives a similar output:

```
_alias_tips__preexec:17: argument list too long: python
zsh: argument list too long: ls
rbenv:11: argument list too long: rbenv
rbenv:11: argument list too long: rbenv
prompt_background_jobs:1: argument list too long: wc
prompt_background_jobs:2: argument list too long: awk
```

If I checkout commit `5a2a92f` the problem goes away. Any ideas? 

zsh version: 5.2
zplug version 2.1.0

**Comment by djui** [comment]
Hi and thanks for reporting. Could you provide you provide some additional info:

- OSX (macOS beta) version
- Python version
- Output of `$ functions | wc -l`
- Output of `$ functions | grep "() {" | wc -l`
- Output of `$ alias | wc -l`

I suspect the I introduced a bug in 99042f1098e6d08d510e910d2c5682f0bb4b156a likely related to escaping. Will investigate.

**Comment by exitface** [comment]
Of course, here you go. Thanks!

```
Arch Linux 
4.6.2-1-ARCH #1 SMP PREEMPT x86_64 GNU/Linux

Python 
3.5.2

functions | wc -l 
10336

functions | grep "() {" | wc -l 
1460

alias | wc -l
188
```

**Comment by djui** [comment]
Could you try 3757e42901e2df90228eb802299095beccc5636f ? It's a blind shot, as I can't reproduce the problem here, currently. I'll try it tomorrow on another setup hopefully reproducing it.

If it is what I think is it, I will have to schedule a complete rewrite soon as the interaction between zsh and python script is getting "suboptimal".

**Comment by exitface** [comment]
That fixed it for me actually, thanks!

**Comment by djui** [comment]
Great, will merge.
